Add Dokka documentation to artifacts
SpineEventEngine/time pull request #140
Opened 2022-04-15 07:28 UTC by tripolkaandrey

This PR adds Dokka-generated documentation as a publish artifact. 

It is done by using functionality introduced in [this PR in config](https://github.com/SpineEventEngine/config/pull/352).

Also, while updating the config, the outdated `groovy` directory was removed.

## Important details
In the `2.11.0` version of `error_prone_core`, they broke their contract which lead to a compilation error. To resolve this issue the previous version was forced.

2022-04-15 09:45 UTC, tripolkaandrey commented on pom.xml
> +  <dependency>
@sonartype-lift ignore

2022-04-15 10:06 UTC, tripolkaandrey commented
Vulnerabilities regarding Dokka dependencies can be fixed only by adding dependency constraints in the [`config`](https://github.com/SpineEventEngine/config) repository because it is a transitive dependency of the precompiled script `dokka-for-java`. 

The vulnerability of `error_prone_core` is not relevant as this dependency is forced to [`2.10.0`](https://mvnrepository.com/artifact/com.google.errorprone/error_prone_core/2.10.0) which uses [`30.1-jre`](https://mvnrepository.com/artifact/com.google.guava/guava/30.1-jre) with no mentioned vulnerabilities.

2022-04-15 10:06 UTC, tripolkaandrey commented on pom.xml
> +  <dependency>
@sonatype-lift ignore

2022-04-15 10:07 UTC, tripolkaandrey commented on pom.xml
> +  <dependency>
@sonatype-lift ignore

2022-04-15 10:07 UTC, tripolkaandrey commented on pom.xml
> +  <dependency>
@sonatype-lift ignore

2022-04-15 10:08 UTC, tripolkaandrey commented on pom.xml
> +  <dependency>
@sonatype-lift ignore

2022-04-15 10:08 UTC, tripolkaandrey commented on pom.xml
>    <dependency>
@sonatype-lift ignore

2022-04-15 10:10 UTC, tripolkaandrey commented on pom.xml
> +  <dependency>
@sonatype-lift ignore

2022-04-15 10:11 UTC, tripolkaandrey commented on pom.xml
> +  <dependency>
@sonatype-lift ignore

2022-04-15 11:00 UTC, tripolkaandrey commented on pom.xml
> +  <dependency>
@sonatype-lift ignore

2022-04-15 11:00 UTC, tripolkaandrey commented on pom.xml
> +  <dependency>
@sonatype-lift ignore

2022-04-15 11:00 UTC, tripolkaandrey commented on pom.xml
> +  <dependency>
@sonatype-lift ignore

2022-04-15 11:00 UTC, tripolkaandrey commented on pom.xml
> +  <dependency>
@sonatype-lift ignore

2022-04-15 11:00 UTC, tripolkaandrey commented on pom.xml
> +  <dependency>
@sonatype-lift ignore

2022-04-15 11:00 UTC, tripolkaandrey commented on pom.xml
> +  <dependency>
@sonatype-lift ignore

2022-04-15 11:00 UTC, tripolkaandrey commented on pom.xml
>    <dependency>
@sonatype-lift ignore

2022-04-15 11:11 UTC, tripolkaandrey commented on pom.xml
> +  <dependency>
@sonatype-lift ignore

2022-04-15 11:11 UTC, tripolkaandrey commented on pom.xml
> +  <dependency>
@sonatype-lift ignore

2022-04-15 11:11 UTC, tripolkaandrey commented on pom.xml
>    <dependency>
@sonatype-lift ignore

2022-04-15 11:11 UTC, tripolkaandrey commented on pom.xml
> +  <dependency>
@sonatype-lift ignore

2022-04-15 11:11 UTC, tripolkaandrey commented on pom.xml
> +  <dependency>
@sonatype-lift ignore

2022-04-15 11:11 UTC, tripolkaandrey commented on pom.xml
> +  <dependency>
@sonatype-lift ignore

2022-04-15 11:11 UTC, tripolkaandrey commented on pom.xml
> +  <dependency>
@sonatype-lift ignore

2022-04-15 11:24 UTC, armiol requested changes
@tripolkaandrey please see my comment. LGTM otherwise.

2022-04-15 11:24 UTC, armiol commented on .idea/misc.xml
> +        <list size="14">
Please make sure this file looks more like the [original one](https://github.com/SpineEventEngine/config/blob/master/.idea/misc.xml).

I don't think we really need all these `@Nullable`-related annotations.

2022-04-18 06:28 UTC, tripolkaandrey commented on pom.xml
> +  <dependency>
@sonatype-lift ignore

2022-04-18 06:28 UTC, tripolkaandrey commented on pom.xml
> +  <dependency>
@sonatype-lift ignore

2022-04-18 06:28 UTC, tripolkaandrey commented on pom.xml
> +  <dependency>
@sonatype-lift ignore

2022-04-18 06:28 UTC, tripolkaandrey commented on pom.xml
>    <dependency>
@sonatype-lift ignore

2022-04-18 06:28 UTC, tripolkaandrey commented on pom.xml
> +  <dependency>
@sonatype-lift ignore

2022-04-18 06:28 UTC, tripolkaandrey commented on pom.xml
> +  <dependency>
@sonatype-lift ignore

2022-04-18 06:28 UTC, tripolkaandrey commented on pom.xml
> +  <dependency>
@sonatype-lift ignore

2022-04-22 15:10 UTC, tripolkaandrey commented
It was closed in favour of a new PR.

2022-04-22 15:10 UTC, closed without merging